### ISSUE TITLE
Lien vers les CGU

### ISSUE THREAD

**Issue by essembeh** [betagouv/mon-aide-cyber#442]
Peut être est-ce lié au fait que l'outil soit en beta et que l'Aidé n'ai pas d'accès propre à l'outil (il me semble?) pour lire et accepter les CGU, mais ce serait pratique d'avoir un lien vers ces CGU dans la question 1

![Capture d’écran du 2024-04-15 22-28-16](https://github.com/betagouv/mon-aide-cyber/assets/669337/61152f87-7534-4172-82ea-bd7441e5fa87)

Une solution pourrait être un PDF que l'on puisse envoyer aux entreprises afin qu'elles en prennent connaissance avant le diag.

**Comment by tomibennett** [comment]
Bonjour @essembeh,

Merci pour ce feedback et cette proposition. La présence de cette question est temporaire et sert, à la reconnaissance de la signature des CGU de l'aidé en l'absence d'un système plus abouti. L'énergie et le temps seront investis à la conception de ce dernier et permettra, une fois en place, de retirer la question. 

> Une solution pourrait être un PDF que l'on puisse envoyer aux entreprises afin qu'elles en prennent connaissance avant le diag.

C'est bien le parcours de l'aidé qui est prévu à travers la [demande d'aide](https://demo.monaidecyber.ssi.gouv.fr/demande-aide). Le cas où (le représentant de) l'entité (publique ou privée) n'a pas signé les CGU avant l'entretien du diagnostic n'est pas encouragé pour le moment.

**Comment by bbougon** [comment]
Bonjour @essembeh ,

Je clos cette issue car ce sujet n’est plus d’actualité : 
- la question n’est plus posée
- le parcours Aidé a été revu ainsi que le lancement du diagnostic

**Comment by essembeh** [comment]
J'ai fait un diag cet après midi et justement j'ai été confronté à ce problème.

Lors de la création d'un diag, il y a le forumaire suivant:

![Capture d’écran du 2024-11-19 19-35-41](https://github.com/user-attachments/assets/17e7d6b1-12f1-41d6-999a-a6d070f3c1ed)

Les trois liens renvoient à la page de présentation, mais pas *directement* aux CGU. 
Le second lien en particulier pourrait envoyer (comme son nom le laisse penser) *directement* au formulaire, ce serait pratique car il faut cliquer sur un lien de ce formulaire pour voir les CGU, tout en base de la page:

![Capture d’écran du 2024-11-19 19-34-30](https://github.com/user-attachments/assets/af1cad24-ca63-4cd1-83be-d9e78a6481e3)

C'est un peu confus, même si mon interlocuteur avait cliqué sur "J'accepte les CGU" il ne les avait pas vraiment lues ...
Ce serait bien de simplement avoir la meme poppup avec les CGU sur ce formulaire de nouveau diag sur le compte Aidant.


Au passage, les trois lien en rouge dans la capture plus haut ne sont pas cohérent je crois
* Le lien No 1: `https://monaidecyber.ssi.gouv.fr/beneficier-du-dispositif/etre-aide`
* Le lien No 2: `https://monaidecyber.ssi.gouv.fr/beneficier-du-dispositif/etre-aide`
* Le lien No 3: `https://monaide.cyber.gouv.fr/beneficier-du-dispositif/etre-aide`

Je me permets de ré ouvrir ce ticket, au moins pour la question d'uniformiser les liens.

**Comment by bbougon** [comment]
Bonjour Sébastien,

Merci pour ton retour, nous le prenons en compte, je viens de le partager
avec l’équipe.

Je ne manquerai pas de te tenir au courant sur l’avancée de ta proposition.

*Bertrand Bougon*
Développeur en prestation pour *MonAideCyber*
Laboratoire d'innovation de l'ANSSI
+33 (0) 6 61 97 07 38
monaidecyber.ssi.gouv.fr



Le mar. 19 nov. 2024 à 19:43, Sébastien MB ***@***.***> a
écrit :
